# Generated by Django 5.2.3 on 2025-06-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
